// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwkFJG3E45byw8RKGDAoPO9jyH4I5_L5Y',
    appId: '1:945099815780:web:1c1df3f026dfb82df75871',
    messagingSenderId: '945099815780',
    projectId: 'force-players-register--app',
    authDomain: 'force-players-register--app.firebaseapp.com',
    storageBucket: 'force-players-register--app.firebasestorage.app',
    measurementId: 'G-VH2M7FNGWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiz6DHlI8Q0WveCToeOVzZVn5oygJqpi4',
    appId: '1:945099815780:android:5a15e55072319df2f75871',
    messagingSenderId: '945099815780',
    projectId: 'force-players-register--app',
    storageBucket: 'force-players-register--app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDahcM4Au4r1gVEZ26-UFANogke1nUk-Kw',
    appId: '1:945099815780:ios:c926a00fc0a35716f75871',
    messagingSenderId: '945099815780',
    projectId: 'force-players-register--app',
    storageBucket: 'force-players-register--app.firebasestorage.app',
    iosBundleId: 'com.example.forcePlayerRegisterApp',
  );
}
